### ISSUE TITLE
Does one have to use your tt_address fork or is it just recommended?

### ISSUE THREAD

**Issue by AndreasA** [Ecodev/formule_newsletter#9]
Is the tt_address fork recommended or required?

Also: Why is a for necessary, wouldn't be enough to extend the TCA by using TCA/Overrides?
If it is necessary and one has a own tt_adress fork already, what would need to be added to make it work?

**Comment by fabarea** [comment]
In the forked tt_address mentioned in the docs we only kept the data structure and remove all plugin code since we never used it - legacy code. That's the main reason.

**Comment by AndreasA** [comment]
Ah sorry, So it removes, the plugin and adds vidi support and add categories optional?
So I guess it isn't required for the newsletter but if one wants to use it with vidi, one needs to add the grid information to the TCA? (or just use your fork :) )

**Comment by fabarea** [comment]
Exactly. The Grid information for Vidi is already in the [forked tt_address](https://github.com/Ecodev/tt_address/blob/master/Configuration/TCA/tt_address.php#L405). On the top, this extension adds more fields regarding token, token validation (cf. TCA/Overrides/tt_addresses.php)
